ao-bringup: Get turnon_telemini working
This script now does complete testing of the board

Signed-off-by: Keith Packard <keithp@keithp.com>

diff --git a/ao-bringup/turnon_easymini b/ao-bringup/turnon_easymini
--- a/ao-bringup/turnon_easymini
+++ b/ao-bringup/turnon_easymini
@@ -20,7 +20,8 @@ fi
 
 VERSION=1.0
 PRODUCT=EasyMini
-#VERSION=0.1
+BASE=`echo $PRODUCT | tr 'A-Z' 'a-z'`
+echo $FILE
 
 echo "$PRODUCT v$VERSION Turn-On and Calibration Program"
 echo "Copyright 2010 by Bdale Garbee.  Released under GPL v2"
@@ -34,23 +35,24 @@ read SERIAL
 
 echo $FLASH_LPC
 
-$FLASH_LPC ../src/easymini-v$VERSION/flash-loader/*.elf || exit 1
+$FLASH_LPC ../src/$BASE-v$VERSION/flash-loader/$BASE-v$VERSION-altos-flash-*.elf || exit 1
+
+sleep 1
+
+echo $USBLOAD
+
+$USBLOAD --serial=$SERIAL ../src/$BASE-v$VERSION/*.ihx || exit 1
 
 sleep 2
 
-$USBLOAD --serial=$SERIAL ../src/easymini-v$VERSION/*.ihx || exit 1
-#$USBLOAD --serial=$SERIAL /usr/share/altos/telemega-v$VERSION*.ihx || exit 1
-
-sleep 2
-
-dev=`ao-list | awk '/$PRODUCT-v'"$VERSION"'/ { print $3; exit(0); }'`
+dev=`ao-list | awk '/'"$PRODUCT"'-v'"$VERSION"'/ { print $3; exit(0); }'`
 
 case "$dev" in
 /dev/tty*)
 	echo "$PRODUCT found on $dev"
 	;;
 *)
-	echo 'No $PRODUCT-v'"$VERSION"' found'
+	echo 'No '"$PRODUCT"'-v'"$VERSION"' found'
 	exit 1
 	;;
 esac
@@ -76,3 +78,19 @@ case $? in
 	echo "failed"
 	exit 1
 esac
+
+FLASHSIZE=1048576
+
+echo "Testing flash"
+./test-flash "$dev" "$FLASHSIZE"
+
+case $? in
+0)
+	;;
+*)
+	echo "failed"
+	exit 1
+esac
+
+echo "$PRODUCT-v$VERSION" serial "$SERIAL" is ready to ship
+exit 0
